### ISSUE TITLE
Define color cases

### ISSUE THREAD

**Issue by daltonos** [daltonos/dbcdashboard#15] opened 2018-06-29 17:21 UTC
@David-RHP 
For each case, define what color should be shown, and what label.

- max < in < out
- out < in < max
- in < min
- in > out AND in > max

Please list other cases if necessary, or place a comment for the ones that don't really exist.

**Comment by davidrhp** [comment] 2018-07-01 22:21
Couldn't I just have the logic implemented on the server and send you the label string in the json? Would that be more efficient or is that such a minor computation that it wouldn't matter?

**Comment by daltonos** [comment] 2018-07-01 23:29
You still need to define the cases, and tell me which action will happen for each. The label itself could come from the server, but at first it's better to hardcode it on the UI.

In any case I need to know the meaning of each case to imagine how to display it on the UI.

**Comment by daltonos** [comment] 2018-07-01 23:30
Visual logic should be on the UI, even if the business logic is

**Comment by davidrhp** [comment] 2018-07-02 15:31
@daltonos 
**Value Constraints (always true):**
- all values: >= 0
- min <= max
- in <= out
- out <= max * 2

**New Variable:**
duid = days_until_issue_date (or however else you'd call that - I don't particularly like this name)
duid: _business_ day until the issue date of the project, e.g., 2 weeks until the issue date == 10 days (Mo through Friday == 5 days)

**Color Coding:**
red: #a90d37
blue: #2a588d

The color of the bar should always be blue except for the cases below. The color change should occur if _either_ of the cases below applies. If 2 cases apply at the same time, the order (highest first) decides which color to use:

- in == max: green
- in < min AND duid > 15: grey
- in > max: grey
- in < min: red
- in > min AND in < max: yellow

_side note:_ I'll probably tweak the color codes in the future.

**Labels:*
Please use a generic placeholder for now. I'll think about appropriate descriptions.

**Comment by daltonos** [comment] 2018-07-02 16:25
Thanks for this info.

**Comment by daltonos** [comment] 2018-07-05 17:54
@david-rhp could you also define the message to be shown on each of these cases?

in == max: green
in < min AND duid > 15: grey
in > max: grey
in < min: red
in > min AND in < max: yellow

**Comment by davidrhp** [comment] 2019-08-03 19:46
The issue is not relevant anymore and won't be fixed/implemented.

**Closed as completed by davidrhp** 2019-08-03 19:46 UTC
Labels: enhancement, UI, UX
